apiVersion: v1
kind: Pod
metadata:
  name: pod-secretsmanager
spec:
  containers:
  - name: pod-secretsmanager
    image: paavanmistry/node-aws-sm-demo:latest
    env:
      - name: ENDPOINT
        value: "https://secretsmanager.us-west-2.amazonaws.com"
      - name: REGION
        value: "us-west-2"
      - name: SECRETNAME
        value: "sm-demo-secret"
  restartPolicy: Never